services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
      - "8081:8081" 
    depends_on:
      - db
    environment:
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ForexAlertDbConnectionString=${ForexAlertDbConnectionString}
      
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: