namespace forex.insights.api.DataModels
{
    /// <summary>
    /// Error response generated by the API.
    /// </summary>
    public class ApiErrorResponse(IEnumerable<string> errors)
    {
        /// <summary>
        /// Errors.
        /// </summary>
        public IEnumerable<string> Errors { get; set; } = errors;
    }
}
